{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "post_service_new_post",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "post_service_new_post_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "post_service_get_post",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "post_service_get_post_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "post service hit total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "post_service_hits_total", "legendFormat": "__auto" }
   ]
  }
 ]
}