

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'grpc_server'
    static_configs:
      # - targets: ['host.docker.internal:9090']
      - targets: ['host.docker.internal:9999']

  # - job_name: 'post'
  #   static_configs:
  #     - targets: ['post:8090']

  