version: "3.8"

services:
    mysql:
        image: mysql:8.3.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: post
        ports:
            - "3309:3306"

    zookeeper:
        image: "bitnami/zookeeper:3.8-debian-10"
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        restart: always

    kafka:
        image: "bitnami/kafka:3.1-debian-10"
        ports:
            - "29092:29092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:29092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
        restart: always

