// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: user_core/v1/user.proto

package userv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Picture       string                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,99,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,100,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_user_core_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Account) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Account) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_core_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_core_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_user_core_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSessionRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_user_core_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_user_core_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccountRequest) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_user_core_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAccountResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"` // must pass id, can only modify name, picture, role
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_user_core_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAccountRequest) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type UpdateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountResponse) Reset() {
	*x = UpdateAccountResponse{}
	mi := &file_user_core_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountResponse) ProtoMessage() {}

func (x *UpdateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_user_core_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_user_core_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type FindAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAccountRequest) Reset() {
	*x = FindAccountRequest{}
	mi := &file_user_core_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAccountRequest) ProtoMessage() {}

func (x *FindAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAccountRequest.ProtoReflect.Descriptor instead.
func (*FindAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *FindAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       []*Account             `protobuf:"bytes,1,rep,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAccountResponse) Reset() {
	*x = FindAccountResponse{}
	mi := &file_user_core_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAccountResponse) ProtoMessage() {}

func (x *FindAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAccountResponse.ProtoReflect.Descriptor instead.
func (*FindAccountResponse) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *FindAccountResponse) GetAccount() []*Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type AccountSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiryTimeMs  uint64                 `protobuf:"varint,2,opt,name=expiry_time_ms,json=expiryTimeMs,proto3" json:"expiry_time_ms,omitempty"` // TIMESTAMP_MS
	AccountId     uint64                 `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountSession) Reset() {
	*x = AccountSession{}
	mi := &file_user_core_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSession) ProtoMessage() {}

func (x *AccountSession) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSession.ProtoReflect.Descriptor instead.
func (*AccountSession) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *AccountSession) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AccountSession) GetExpiryTimeMs() uint64 {
	if x != nil {
		return x.ExpiryTimeMs
	}
	return 0
}

func (x *AccountSession) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type CheckFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentId     string                 `protobuf:"bytes,1,opt,name=current_id,json=currentId,proto3" json:"current_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFollowingRequest) Reset() {
	*x = CheckFollowingRequest{}
	mi := &file_user_core_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFollowingRequest) ProtoMessage() {}

func (x *CheckFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFollowingRequest.ProtoReflect.Descriptor instead.
func (*CheckFollowingRequest) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *CheckFollowingRequest) GetCurrentId() string {
	if x != nil {
		return x.CurrentId
	}
	return ""
}

func (x *CheckFollowingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Following     bool                   `protobuf:"varint,1,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFollowingResponse) Reset() {
	*x = CheckFollowingResponse{}
	mi := &file_user_core_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFollowingResponse) ProtoMessage() {}

func (x *CheckFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFollowingResponse.ProtoReflect.Descriptor instead.
func (*CheckFollowingResponse) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *CheckFollowingResponse) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type GetFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingRequest) Reset() {
	*x = GetFollowingRequest{}
	mi := &file_user_core_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRequest) ProtoMessage() {}

func (x *GetFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *GetFollowingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []string               `protobuf:"bytes,1,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingResponse) Reset() {
	*x = GetFollowingResponse{}
	mi := &file_user_core_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingResponse) ProtoMessage() {}

func (x *GetFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_core_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return file_user_core_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetFollowingResponse) GetUserId() []string {
	if x != nil {
		return x.UserId
	}
	return nil
}

var File_user_core_v1_user_proto protoreflect.FileDescriptor

const file_user_core_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x17user_core/v1/user.proto\x12\auser.v1\x1a\x1cgoogle/api/annotations.proto\"\xd0\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"created_at\x18c \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18d \x01(\tR\tupdatedAt\"C\n" +
	"\fLoginRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"=\n" +
	"\rLoginResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"A\n" +
	"\x14CreateSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"-\n" +
	"\x15CreateSessionResponse\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"B\n" +
	"\x14CreateAccountRequest\x12*\n" +
	"\aaccount\x18\x01 \x01(\v2\x10.user.v1.AccountR\aaccount\"'\n" +
	"\x15CreateAccountResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"B\n" +
	"\x14UpdateAccountRequest\x12*\n" +
	"\aaccount\x18\x01 \x01(\v2\x10.user.v1.AccountR\aaccount\"C\n" +
	"\x15UpdateAccountResponse\x12*\n" +
	"\aaccount\x18\x01 \x01(\v2\x10.user.v1.AccountR\aaccount\"+\n" +
	"\x11GetAccountRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x12GetAccountResponse\x12*\n" +
	"\aaccount\x18\x01 \x01(\v2\x10.user.v1.AccountR\aaccount\",\n" +
	"\x12FindAccountRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x13FindAccountResponse\x12*\n" +
	"\aaccount\x18\x01 \x03(\v2\x10.user.v1.AccountR\aaccount\"k\n" +
	"\x0eAccountSession\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12$\n" +
	"\x0eexpiry_time_ms\x18\x02 \x01(\x04R\fexpiryTimeMs\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x04R\taccountId\"O\n" +
	"\x15CheckFollowingRequest\x12\x1d\n" +
	"\n" +
	"current_id\x18\x01 \x01(\tR\tcurrentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"6\n" +
	"\x16CheckFollowingResponse\x12\x1c\n" +
	"\tfollowing\x18\x01 \x01(\bR\tfollowing\".\n" +
	"\x13GetFollowingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"/\n" +
	"\x14GetFollowingResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x03(\tR\x06userId2\xc3\a\n" +
	"\x0eAccountService\x12j\n" +
	"\rCreateAccount\x12\x1d.user.v1.CreateAccountRequest\x1a\x1e.user.v1.CreateAccountResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/account\x12g\n" +
	"\n" +
	"GetAccount\x12\x1a.user.v1.GetAccountRequest\x1a\x1b.user.v1.GetAccountResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/account/{userId}\x12a\n" +
	"\vFindAccount\x12\x1b.user.v1.FindAccountRequest\x1a\x1c.user.v1.FindAccountResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/account\x12P\n" +
	"\x05Login\x12\x15.user.v1.LoginRequest\x1a\x16.user.v1.LoginResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/login\x12q\n" +
	"\rCreateSession\x12\x1d.user.v1.CreateSessionRequest\x1a\x1e.user.v1.CreateSessionResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/create_session\x12f\n" +
	"\fGetFollowing\x12\x1c.user.v1.GetFollowingRequest\x1a\x1d.user.v1.GetFollowingResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/following\x12m\n" +
	"\x0fCreateFollowing\x12\x1e.user.v1.CheckFollowingRequest\x1a\x1f.user.v1.CheckFollowingResponse\"\x19\x82\xd3\xe4\x93\x02\x13\"\x11/api/v1/following\x12m\n" +
	"\x0fDeleteFollowing\x12\x1e.user.v1.CheckFollowingRequest\x1a\x1f.user.v1.CheckFollowingResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/v1/following\x12n\n" +
	"\x0eCheckFollowing\x12\x1e.user.v1.CheckFollowingRequest\x1a\x1f.user.v1.CheckFollowingResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/isFollowingBy\n" +
	"\vcom.user.v1B\tUserProtoP\x01Z\"gateway_sevice/user_core/v1;userv1\xa2\x02\x03UXX\xaa\x02\aUser.V1\xca\x02\aUser\\V1\xe2\x02\x13User\\V1\\GPBMetadata\xea\x02\bUser::V1b\x06proto3"

var (
	file_user_core_v1_user_proto_rawDescOnce sync.Once
	file_user_core_v1_user_proto_rawDescData []byte
)

func file_user_core_v1_user_proto_rawDescGZIP() []byte {
	file_user_core_v1_user_proto_rawDescOnce.Do(func() {
		file_user_core_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_core_v1_user_proto_rawDesc), len(file_user_core_v1_user_proto_rawDesc)))
	})
	return file_user_core_v1_user_proto_rawDescData
}

var file_user_core_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_user_core_v1_user_proto_goTypes = []any{
	(*Account)(nil),                // 0: user.v1.Account
	(*LoginRequest)(nil),           // 1: user.v1.LoginRequest
	(*LoginResponse)(nil),          // 2: user.v1.LoginResponse
	(*CreateSessionRequest)(nil),   // 3: user.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 4: user.v1.CreateSessionResponse
	(*CreateAccountRequest)(nil),   // 5: user.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil),  // 6: user.v1.CreateAccountResponse
	(*UpdateAccountRequest)(nil),   // 7: user.v1.UpdateAccountRequest
	(*UpdateAccountResponse)(nil),  // 8: user.v1.UpdateAccountResponse
	(*GetAccountRequest)(nil),      // 9: user.v1.GetAccountRequest
	(*GetAccountResponse)(nil),     // 10: user.v1.GetAccountResponse
	(*FindAccountRequest)(nil),     // 11: user.v1.FindAccountRequest
	(*FindAccountResponse)(nil),    // 12: user.v1.FindAccountResponse
	(*AccountSession)(nil),         // 13: user.v1.AccountSession
	(*CheckFollowingRequest)(nil),  // 14: user.v1.CheckFollowingRequest
	(*CheckFollowingResponse)(nil), // 15: user.v1.CheckFollowingResponse
	(*GetFollowingRequest)(nil),    // 16: user.v1.GetFollowingRequest
	(*GetFollowingResponse)(nil),   // 17: user.v1.GetFollowingResponse
}
var file_user_core_v1_user_proto_depIdxs = []int32{
	0,  // 0: user.v1.CreateAccountRequest.account:type_name -> user.v1.Account
	0,  // 1: user.v1.UpdateAccountRequest.account:type_name -> user.v1.Account
	0,  // 2: user.v1.UpdateAccountResponse.account:type_name -> user.v1.Account
	0,  // 3: user.v1.GetAccountResponse.account:type_name -> user.v1.Account
	0,  // 4: user.v1.FindAccountResponse.account:type_name -> user.v1.Account
	5,  // 5: user.v1.AccountService.CreateAccount:input_type -> user.v1.CreateAccountRequest
	9,  // 6: user.v1.AccountService.GetAccount:input_type -> user.v1.GetAccountRequest
	11, // 7: user.v1.AccountService.FindAccount:input_type -> user.v1.FindAccountRequest
	1,  // 8: user.v1.AccountService.Login:input_type -> user.v1.LoginRequest
	3,  // 9: user.v1.AccountService.CreateSession:input_type -> user.v1.CreateSessionRequest
	16, // 10: user.v1.AccountService.GetFollowing:input_type -> user.v1.GetFollowingRequest
	14, // 11: user.v1.AccountService.CreateFollowing:input_type -> user.v1.CheckFollowingRequest
	14, // 12: user.v1.AccountService.DeleteFollowing:input_type -> user.v1.CheckFollowingRequest
	14, // 13: user.v1.AccountService.CheckFollowing:input_type -> user.v1.CheckFollowingRequest
	6,  // 14: user.v1.AccountService.CreateAccount:output_type -> user.v1.CreateAccountResponse
	10, // 15: user.v1.AccountService.GetAccount:output_type -> user.v1.GetAccountResponse
	12, // 16: user.v1.AccountService.FindAccount:output_type -> user.v1.FindAccountResponse
	2,  // 17: user.v1.AccountService.Login:output_type -> user.v1.LoginResponse
	4,  // 18: user.v1.AccountService.CreateSession:output_type -> user.v1.CreateSessionResponse
	17, // 19: user.v1.AccountService.GetFollowing:output_type -> user.v1.GetFollowingResponse
	15, // 20: user.v1.AccountService.CreateFollowing:output_type -> user.v1.CheckFollowingResponse
	15, // 21: user.v1.AccountService.DeleteFollowing:output_type -> user.v1.CheckFollowingResponse
	15, // 22: user.v1.AccountService.CheckFollowing:output_type -> user.v1.CheckFollowingResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_user_core_v1_user_proto_init() }
func file_user_core_v1_user_proto_init() {
	if File_user_core_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_core_v1_user_proto_rawDesc), len(file_user_core_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_core_v1_user_proto_goTypes,
		DependencyIndexes: file_user_core_v1_user_proto_depIdxs,
		MessageInfos:      file_user_core_v1_user_proto_msgTypes,
	}.Build()
	File_user_core_v1_user_proto = out.File
	file_user_core_v1_user_proto_goTypes = nil
	file_user_core_v1_user_proto_depIdxs = nil
}
