kafka:
  addresses: 127.0.0.1:29092
  client_id: "newsfeed"
grpc:
  user_service_address: "0.0.0.0:5600"
  post_service_address: "0.0.0.0:5601"

database:
  host: 127.0.0.1
  port: 3309
  username: root
  password: root
  database: network
  
redis:
  address: "127.0.0.1:6379"
  username: ""
  password: ""
  databse: 0
  ttl: 86400
