
# run to update buf tool only
buf-update:
	buf dep update .build/protos


# install dependency prepare for generate on device
install:
	bash build.sh install

build:
# example make build PROTO=abc.proto
	bash build.sh build_proto_func ${PROTO}



	

