auth:
  duration: 24h

redis:
  address: "127.0.0.1:6379"
  username: ""
  password: ""
  databse: 0
  ttl: 86400
grpc:
  user_service_address: "0.0.0.0:5600"

database:
  host: 127.0.0.1
  port: 3309
  username: root
  password: root
  database: user