// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/namnv2496/user-service/app"
	"github.com/namnv2496/user-service/internal/cache"
	"github.com/namnv2496/user-service/internal/configs"
	"github.com/namnv2496/user-service/internal/database"
	"github.com/namnv2496/user-service/internal/handler/grpc"
	"github.com/namnv2496/user-service/internal/logic"
)

// Injectors from wire.go:

func Initilize() (*app.App, func(), error) {
	db, cleanup, err := database.NewDatabase()
	if err != nil {
		return nil, nil, err
	}
	goquDatabase := database.InitializeGoquDB(db)
	config, err := configs.NewConfig()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redis := config.Redis
	client := cache.NewRedisClient(redis)
	userService := logic.NewUserService(goquDatabase, client)
	accountServiceServer := grpc.NewGrpcHander(userService)
	server := grpc.NewServer(accountServiceServer)
	appApp := app.NewApp(server)
	return appApp, func() {
		cleanup()
	}, nil
}
