// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/namnv2496/post-service/app"
	"github.com/namnv2496/post-service/internal/configs"
	"github.com/namnv2496/post-service/internal/database"
	"github.com/namnv2496/post-service/internal/handler/grpc"
	"github.com/namnv2496/post-service/internal/logic"
	"github.com/namnv2496/post-service/internal/mq/producer"
)

// Injectors from wire.go:

func Initilize() (*app.App, func(), error) {
	config, err := configs.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	configsDatabase := config.Database
	db, cleanup, err := database.NewDatabase(configsDatabase)
	if err != nil {
		return nil, nil, err
	}
	goquDatabase := database.InitializeGoquDB(db)
	kafka := config.Kafka
	client := producer.NewClient(kafka)
	userService := logic.NewUserService(goquDatabase, client)
	postServiceServer := grpc.NewGrpcHander(userService)
	server := grpc.NewServer(postServiceServer)
	appApp := app.NewApp(server)
	return appApp, func() {
		cleanup()
	}, nil
}
