// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/namnv2496/newsfeed-service/app"
	"github.com/namnv2496/newsfeed-service/internal/cache"
	"github.com/namnv2496/newsfeed-service/internal/configs"
	"github.com/namnv2496/newsfeed-service/internal/database"
	"github.com/namnv2496/newsfeed-service/internal/handler/consumers"
	"github.com/namnv2496/newsfeed-service/internal/handler/grpc"
	"github.com/namnv2496/newsfeed-service/internal/logic"
	"github.com/namnv2496/newsfeed-service/internal/mq/consumer"
)

// Injectors from wire.go:

func Initilize() (*app.App, func(), error) {
	config, err := configs.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	configsDatabase := config.Database
	db, cleanup, err := database.NewDatabase(configsDatabase)
	if err != nil {
		return nil, nil, err
	}
	goquDatabase := database.InitializeGoquDB(db)
	kafka := config.Kafka
	consumerConsumer := consumer.NewConsumer(kafka)
	redis := config.Redis
	client := cache.NewRedisClient(redis)
	newsfeedService := logic.NewUserService(goquDatabase, consumerConsumer, client)
	newsfeedServiceServer := grpc.NewGrpcHander(newsfeedService)
	server := grpc.NewServer(newsfeedServiceServer)
	configsGRPC := config.GRPC
	productGRPCClient, err := grpc.NewGRPCProductClient(configsGRPC)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	consumerHandler := consumers.NewKafkaHandler(consumerConsumer, newsfeedService, productGRPCClient)
	appApp := app.NewApp(server, consumerHandler)
	return appApp, func() {
		cleanup()
	}, nil
}
