// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/namnv2496/http_gateway/internal/configs"
	"github.com/namnv2496/http_gateway/internal/handler/http"
)

// Injectors from wire.go:

func Initialize() (http.Server, error) {
	config, err := configs.NewConfig()
	if err != nil {
		return nil, err
	}
	gateway := config.Gateway
	grpc := config.GRPC
	auth := config.Auth
	server := http.NewServer(gateway, grpc, auth)
	return server, nil
}
