name: Go Social Network CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true
        
    - name: Install dependencies
      run: |
        cd user-service && go mod download
        cd ../post-service && go mod download
        cd ../newsfeed-service && go mod download
        cd ../http_gateway && go mod download
        cd ../message-service && go mod download

    - name: Run tests
      run: |
        cd user-service && go test ./...
        cd ../post-service && go test ./...
        cd ../newsfeed-service && go test ./...
        cd ../http_gateway && go test ./...
        cd ../message-service && go test ./...