name: Go Social Network CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true
        
    - name: Install dependencies
      run: |
        go mod download
        cd user-service && go mod download
        cd ../post-service && go mod download
        cd ../newsfeed-service && go mod download
        cd ../http_gateway && go mod download
        cd ../message-service && go mod download

    - name: Run tests
      run: |
        cd user-service && go test -v ./...
        cd ../post-service && go test -v ./...
        cd ../newsfeed-service && go test -v ./...
        cd ../http_gateway && go test -v ./...
        cd ../message-service && go test -v ./...

  build:
    name: Build Services
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push user-service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: user-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest

    - name: Build and push post-service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: post-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/post-service:latest

    - name: Build and push newsfeed-service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: newsfeed-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/newsfeed-service:latest

    - name: Build and push http-gateway
      uses: docker/build-push-action@v5
      with:
        context: .
        file: http_gateway/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/http-gateway:latest

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...